version: "3"
services:
  postgres:
    image: "postgres:11"
    container_name: "postgres"
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: p@ssw0rd

networks:
  default:
    driver: bridge