version: "3"
services:
  postgres:
    container_name: corrida-robotica-api
    restart: always
    image: "postgres:latest"
    container_name: "postgres"
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME} 
      POSTGRES_DB: ${DB_DATABASE}

networks:
  default:
    driver: bridge